const axios = require('axios')
const _ = require('lodash')
const yellowData = require('yellow/src/data/main')
const metadataRequest = require('./metadata')
module.exports = axios.get('/data').then((response) => metadataRequest.then((metadata) => new yellowData.Data(response.data, metadata)))
